[#abilities]

= Abilities

== Non-combat abilities

Choose a non-combat related activity for which you're *good* at die rolls. It's up to agreement between players and GM as to how specific the ability is. If one player wants to be "good at forensic accounting" and another wants to be "good at being a detective", that's fine as long as everyone is clear about when it applies. Clarify with the GM whether particular circumstances are appropriate for an ability before rolling the dice, don't argue for rerolls after the fact.

== Combat abilities

Combat abilities are more specific. Each bullet point below is a separate ability, e.g. *good* at initiative is separate from being able to rally your team, even though both are under the Leader section. Many abilities are specific to using particular items, e.g. being *good* at 2H melee is different from being *good* at 1H melee. Not all items have corresponding abilities for particular modifiers, this is intentional. Some abilities have explicit dependencies on another ability, but otherwise you can choose them in any order during advancement.

In addition to *good*, combat abilities may grant the die roll modifiers *precise* or *powerful*. *Precise* means that after a hit location die is chosen for a successful roll, you can adjust that die up or down by 1. *Powerful* means that after a damage die is chosen for a successful roll, you can adjust that die up by 1. You cannot adjust above 9 or below 0. You can use only one of *good*, *precise*, or *powerful* for a given roll, after seeing the initial result. Note that unlike *good*, *precise* and *powerful* do not modify chance of success, only the effect of the success.

=== Shield

* *Good* Defend.
* Can use your action to Defend another character.
* Can Attack using a shield.
* Can declare All-Out Defend after initiative but before any actions in a turn. During that turn you may Defend all attacks against you, but those rolls are not *good* and cannot be critical. During that turn you cannot take any other actions, and cannot defend other characters.

=== First Aid

* *Good* First Aid.
* Before rolling for First Aid, you can instead choose to automatically succeed and erase only 1 \ mark, replacing the rest with X.

=== 2H Melee

* *Good* 2H melee Attack.
* *Good* 2H melee Intercept and Counterattack.
* *Powerful* 2H melee Attack.
* *Precise* 2H melee Attack.
* On a critical success, in addition to one of the standard effects, you can destroy 1 slot worth of items on your target.
* Cannot be Counterattacked.

=== 1H Melee

* *Good* 1H melee Attack.
* *Good* 1H melee Intercept and Counterattack.
* *Precise* 1H melee Attack.
* On a critical success, instead of gaining another action, you can force your target to lose their next action.

=== 2H Ranged

* *Good* 2H ranged Attack.
* *Good* 2H ranged Intercept.
* *Powerful* 2H ranged Attack.
* *Precise* 2H ranged Attack.
* Line of sight for 2H ranged Attack is prevented by 3 or more cover marks, not 2.

=== 1H Ranged

* *Good* 1H ranged Attack.
* *Precise* 1H ranged Attack.

=== Area of Effect (AoE)

AoE weapons come in different varieties, each requiring a corresponding ability and an item that is destroyed per attempted use. If you have multiple AoE abilities you must specify in advance which items are for which ability. They all use an Attack action, not Counterattack or Intercept, against an area at a range of 0 or 1. Failed AoE rolls have no effect. On a critical failure you take the _sum_ of the dice in damage, reading 100 as 20, 99 as 18, etc.

AoEs cannot be Counterattacked. Neither cover nor shields apply to AoEs. Wounds caused by AoEs can be spread among locations of the damaged character's choice, and can be prevented by armor as normal. Some AoE effects last for a specified number of full turns: 0 ends at the end of the current turn, 1 at the end of the next turn, and so on.

* Blast
* Continuous
* Cover
* Demolish

==== Blast

Make a single attack roll. On success, choose one die for damage, and the other die for number of _additional_ targets in that same area. You choose targets, but must include allies if there are no other remaining targets. If a target spends an action on a successful Defend that beats your roll they take no damage. Otherwise each target takes that amount of damage.

****
You choose an area at a range of 1, mark your AoE item as destroyed, and roll a 42, a success. You choose 4 for damage and 2 for additional targets. There are three enemies and one ally in the area, so you choose the three enemies. One of the enemies successfully Defends with a 50 and takes no damage. The other enemies don't want to spend an action on Defend, so they each take 4 damage. One decides to take all 4 in the torso and destroys the slot of armor there to eliminate the damage. The other decides to take 2 points in each leg.
****

==== Continuous

Make a single attack roll. On success, choose one die for damage, and the other die for the number of turns the effect lasts. While in effect, anyone in that area who starts an action other than Move takes that amount of damage immediately. If there are multiple continuous effects on an area simultaneously, use only the most damaging one.

==== Cover

Make a single attack roll. On success, choose one die for the number of turns the effect lasts. While in effect, that area has cover in all directions.

==== Demolish

Make a single attack roll. On success, all cover in that area is destroyed, regardless of whether it was created by terrain or ability.

=== Leader

* *Good* at initiative rolls. If someone else on your team has higher level, they can choose to let you roll initiative.
* You can use an action to attempt to rally your team. Make a roll, on a success anyone on your team (including you) can increase their level to match the roll. They can't exceed their *max* level. You can attempt this only once per combat, whether you succeed or fail. You can use this ability at the end of combat if you haven't attempted it yet.
* You can use an action to direct someone else on your team to take any action they are able to. If they agree, they can do so without using an action of their own. If they disagree, you can use your action for something else. Someone cannot benefit from this ability more than once per turn, nor if they used this ability this turn.
* When you succeed at an initiative roll, even if you didn't win, gain an additional action that can be used only to direct others. Requires the prior ability.

=== Speed

* You can roll for Move. On a success you can move twice, each subject to Intercept. On a failure you stay in your current area, but it is still treated as a move attempt for Intercept.

=== Stealth

* While in an area without enemies, you gain an additional cover mark between you and any other area. Besides providing cover, this also counts against line of sight, even if there was already cover in your area. You lose this effect as soon as you start an Attack or Intercept action. You regain it after a Move action. Your area can still be targeted by AoEs and you can suffer from their effects, including losing stealth due to Demolish.

=== Unarmed Combat

* Make Attack, Counterattack, or Intercept actions using an empty hand or two legs. This is a prerequisite for any of the following abilities.
* *Good* unarmed Attack.
* *Good* unarmed Counterattack and Intercept.
* *Precise* unarmed Attack.
* When you successfully Intercept with two empty hands, in addition to damage you can stop the target's movement. You decide which of the two areas they end up in.
