[#characters]

= Characters

To create a character, decide on a concept, a name, and a description, then fill in your character sheet.

== Level

Your level is your basic percentage chance of success when <<dice.adoc#dice,rolling dice>>.  Your current and *max* level start at 50, and are tracked separately on your character sheet.  The word 'level' by itself always refers to current level unless prefixed with *max*.

Your level can decrease when you're <<combat.adoc#damage,hurt in combat>> and increase when you <<resting.adoc#resting,rest>>. It can't increase higher than your *max* level. If it reaches zero, you're <<combat.adoc#unconsciousness,unconscious>>.

== Abilities

<<abilities.adoc#abilities,Abilities>> give you different beneficial special rules. You start with one non-combat ability and one combat ability.

== Items

You start with 5 slots for combat related <<items.adoc#items>>. The number and type of non-combat items you can have are up to you, as long as the GM agrees. You can change or replace items when you rest.

Use the top slot(s) on the sheet for the items you typically want in your hands at the start of combat. Items will specify whether they require one or two hands. I'm assuming humanlike physiology, if you want to play an octopus work it out with the GM.

== Advancement

All players' *max* level increases by 1 at the end of a session if they achieved their goal for that session.  Near the beginning of a session the players should agree on a single goal collectively.  The GM may set the scene, and may warn players when a goal isn't likely to be achieveable by the end of a session, but may not choose a goal for the players.

When your level increases to a number ending in 5 you get another slot for items. At level 55 you can have up to 6 combat related items, at level 65 up to 7, etc.

When your level increases to a number ending in 0 you choose another ability. At level 60 you can choose a second combat or non-combat ability, at level 70 another, etc.

Your *max* level can't increase beyond 99.