[#characters]

= Characters

Decide on a concept, a name, and a description, then fill in your character sheet.

== Level

Your level is the number you need for success when <<dice.adoc#dice,rolling dice>>.  Your current and *max* level start at 50, and are tracked separately on your character sheet.  The word 'level' by itself always refers to current level unless prefixed with *max*.

Your level can decrease when you're <<combat.adoc#_damage, damaged>> in combat and increase when you <<combat.adoc#_recovery, recover>>. It cannot increase higher than your *max* level.

== Abilities

<<abilities.adoc#abilities,Abilities>> give you different beneficial special rules. You start with one non-combat ability and one combat ability.

== Items

You start with 5 slots for combat related <<items.adoc#items>>. The number and type of non-combat items you can have are up to you, as long as the GM agrees. You can change or replace items when you <<combat.adoc#_recovery, recover>>.

Use the top slot(s) on the sheet for the items you typically want in your hands at the start of combat. Items will specify whether they require one or two hands. I'm assuming humanlike physiology, if you want to play an octopus work it out with the GM.

== Advancement

All players' *max* level increases by 1 at the end of a session if they achieved their goal for that session.  Near the beginning of a session the players should agree on a single goal collectively.  The GM can set the scene, and can warn players when a goal isn't likely to be achieveable by the end of a session, but cannot choose a goal for the players.

When your level increases to a number ending in 5 you get another slot for items. At level 55 you can have up to 6 combat related items, at level 65 up to 7, etc.

When your level increases to a number ending in 0 you choose another ability. At level 60 you can choose a second combat or non-combat ability, at level 70 another, etc.

Your *max* level cannot increase above 95.
